[build-system]
requires = ["requests 2.26.0","beautifulsoup4 4.10.0"]
build-backend = "flit_core.buildapi"

[project]
name = "AnimeFenix"
authors = [{name = "Raddiactive", discord = "Raddiactive#1886"}]
dynamic = ["1.0", "A simple anime web api"]
